### ISSUE TITLE
Fix ability to create and delete AndroidApps w/ AndroidAppPermissions

### ISSUE THREAD

**Issue by shevtsod** [matryoshkadoll/matryoshka-server#28]
It's currently impossible to delete `AndroidApps` because the associated `AndroidAppPermission`s need to be deleted as well.

I need to move some code out of the API `AndroidApps` controller into the model.

Laravel supports lifecycle hooks into models when certain events happen:

https://laravel.com/docs/5.7/eloquent#events

I'll need to hook into the `creating` and `deleting` events to create and delete the associated `AndroidAppPermission` object.

I should also add tests for updating and deleting AndroidApps.

**Comment by oscar666666** [comment]
I think it is a foreign key issue, the system forbidden us to delete androidapps because there are androidapppermission records associated to that androidapp, if so,  we just need to add onDelete('cascade') to AndroidAppPermission table, to delete androidapppermission records related to that androidapp.

**Comment by shevtsod** [comment]
True, we could enforce it on a database level using the `CASCADE` constraint. My only thought is that, if we do it on the application level like I described in the original post of this issue, it would also allow us to write some logic to create and modify permissions by interacting with the `AndroidApp` object in ways more complex than database constraints. For example we could implement soft-deletions or set default permissions when an `AndroidApp` is created and modify permissions when an `AndroidApp` is updated.

**Comment by shevtsod** [comment]
Closing this because I don't think we'll be using the `AndroidAppPermissions` table after all. It's still in the database but not wired up to anything. Some relevant attributes that this table would have had such as `approved` and `private` are now just part of the `AndroidApps` table.
