### ISSUE TITLE
Make database seeders only run once

### ISSUE THREAD

**Issue by shevtsod** [matryoshkadoll/matryoshka-server#29]
We should modify the seeders we wrote so that each one of them only runs once. The current problem is that if we ever add new seeders that we need to run, we would end up creating duplicates of database records.

i.e.,

```bash
# AndroidApps, Reviews, Replies, etc. are seeded once
php artisan db:seed

# AndroidApps, Reviews, Replies, etc. are seeded again, one duplicate of each in database
php artisan db:seed

# AndroidApps, Reviews, Replies, etc. are seeded again, two duplicates of each in database
php artisan db:seed

# ...
```

But we want this:

```bash
# AndroidApps, Reviews, Replies, etc. are seeded once
php artisan db:seed

# Only records that don't exist yet are seeded, records that already exist are skipped
php artisan db:seed

# Only records that don't exist yet are seeded, records that already exist are skipped
php artisan db:seed

# ...
```

For example, [here is a Voyager seeder that only runs once](https://github.com/matryoshkadoll/matryoshka-server/blob/master/database/seeds/RolesTableSeeder.php) and [here is one of our seeders that will always run](https://github.com/matryoshkadoll/matryoshka-server/blob/master/database/seeds/AndroidAppsTableSeeder.php).

So, we need to make a change like this for every object being seeded:

From:

```php
DB::table('android_apps')->insert([
  [
    'name' => "App 1",
    'version' => "1.0",
    'description' => "Placeholder application 1",
    'price' => 0.00,
    'avatar' => "empty",
  ]
]);
```

To:

```php
$androidApp= AndroidApp::firstOrNew(['name' => "App 1"]);

if (!$role->exists) {
  $role->fill([
    'version' => "1.0",
    'description' => "Placeholder application 1",
    'price' => 0.00,
    'avatar' => "empty",
  ])->save();
}
```

**Comment by shevtsod** [comment]
@oscar666666 Can you please handle this one?

**Comment by oscar666666** [comment]
fixed
