### ISSUE TITLE
AndroidApps

### ISSUE THREAD

**Issue by shevtsod** [matryoshkadoll/matryoshka-server#5]
Requirements for the `AndroidApp` model, i.e., the actual Android Apps that will be hosted by the app store and the functionalities that they will have.

**Comment by shevtsod** [comment]
> Can certain apps be "public", i.e., visible to every user?

Certain apps can be public, certain can be restricted in visibility.

**Comment by shevtsod** [comment]
> Should app purchase/download pages include pictures and videos to promote them?

Yes

**Comment by shevtsod** [comment]
> Should apps have the ability to set age restrictions?

Yes, and admin can override

**Comment by oscar666666** [comment]
1. We cannot find one app and assume every organization allow its users to install it.

2. 

3. Yes

**Comment by shevtsod** [comment]
Need a vendor dashboard. Vendors will see overrides by administrators. Vendors will also be able to upload applications and see their status.
